version: "3.7"

services:
    web:
        image: nginx
        working_dir: /app/public
        volumes:
            - ./app:/app
            - ./configdocker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "5000:80"

    phpfpm:
        build: configdocker/php-fpm
        volumes:
            - ./app:/app
            - ./configdocker/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf

    phpcli:
        build: configdocker/php-cli
        working_dir: /app
        volumes:
            - ./app:/app

    postgres:
        image: postgres
        working_dir: /app
        restart: always    
        volumes:
            - ./app:/app
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
            - POSTGRES_DB=devdb
        ports:
            - "5432:5432"

    mail:
        image: inbucket/inbucket
        ports:
            - "9000:9000"



